spring:
  application:
    name: beheer-service
  jackson:
      serialization:
        write_dates_as_timestamps: false
        #INDENT_OUTPUT: true


eureka:
    instance:
        leaseRenewalIntervalInSeconds: 3
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    client:
        registryFetchIntervalSeconds: 5
        instanceInfoReplicationIntervalSeconds: 5
        initialInstanceInfoReplicationIntervalSeconds: 5

server:
  port: 8084

error:
    whitelabel:
        enabled=true


beheerder-service:
  token:
    header: X-Auth-Token
    secret: flatMap43
    expiration: 604800


logging:
  level:
    root: WARN
    company.tothepoint: DEBUG

---

spring:
  profiles: docker
  data:
    mongodb:
      host: beheer-mongo
  rabbitmq:
      host: rabbitmq
app:
  rabbitmq:
      host: rabbitmq
server:
  port: 8080

eureka:
    instance:
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://discovery:8761/eureka/
---